import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";  // default font
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import HamburgerMenu from "../../components/hamburgerMenu";
import { Analytics } from "@vercel/analytics/react"


const jetBrainsMono = JetBrains_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kendrick ngo is cool",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={jetBrainsMono.className}>
          {children}
          <HamburgerMenu />
          <Analytics />
      </body>
    </html>
  );
}

